### ISSUE TITLE
兄弟 是时候更新clover来支持最新的10.14.4了。

### ISSUE THREAD

**Issue by 911061873** [Doapeat/Dell7567#6]
如题。

**Comment by 911061873** [comment]
还有一个问题就是键盘上的屏幕亮度调节不能使用。可以修复嘛？可以教教我怎么去做这些补丁什么的嘛。晚上的教程看了好多没搞懂。

**Comment by Doapeat** [comment]
补丁这个我也不太懂，更新我看看51有时间就更新，这几天有点忙，不好意思哈

**Comment by Doapeat** [comment]
已经更新了

**Comment by 911061873** [comment]
可以留个联系方式吗？ 有些问题想请教一下。

**Comment by 911061873** [comment]
我有一张1820A再win10下装驱动就蓝屏，机器跟你是一样的 请问你是怎么解决的，还有就是OSX下怎么装驱动，没研究明白。

**Comment by 911061873** [comment]
还有就是为什么不直接上4920版本的clover  而是使用4903
