### ISSUE TITLE
新问题，更新以后进不去安装界面。

### ISSUE THREAD

**Issue by 911061873** [Doapeat/Dell7567#7]
在你更新完成以后说可以支持DW1820A，我打算把系统重装一下。（因为之前折腾过无线网卡驱动，动了系统分区里面的文件。）
于是下载了最新的Clover文件夹，删除了原来U盘里的，复制进去。重启后发现进不去安装界面。
![image](https://user-images.githubusercontent.com/19637526/56992697-37ca8e00-6bcd-11e9-94a2-37daeb410ce1.png)

上网cha le查了下好像是USB的问题导致的。
我正在研究怎么修复。

**Comment by 911061873** [comment]
我尝试恢复我更新以前的备份，然后引导安装U盘，发现仍然进=进不去，错误信息一样。这时候想起来我中途从原装Intel网卡换成来DW1820A，于是进F2把网卡屏蔽，再引导安装U盘，顺利进去了。
说明DW1820A再系统安装完成之前需要屏蔽？

**Comment by Doapeat** [comment]
我没有出现类似问题，不过也可能是个新思路
