### ISSUE TITLE
YE!  我已经搞定了1820A了 

### ISSUE THREAD

**Issue by 911061873** [Doapeat/Dell7567#8]
我用了卖家发我的驱动，很稳定，没有什么不能开关啊，死机之类的问题，基本完美，5GHz速率860Mbps。我待会fork，然后在你的基础上改动一下。
谢谢。

**Comment by Doapeat** [comment]
你看看这个刚写的https://www.jianshu.com/p/6c6c5bf0dc54

**Comment by 911061873** [comment]
方便加个联系方式吗？我微信13718481995
